version: 2

sources:
  - name: brazillian_ecommerce_project
    description: >
      brazillian ecommerce data from kaggle
    database: dsai-module2-project
    schema: brazillian_ecommerce_project
    
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: products
      - name: sellers
      - name: product_category_name_translation