version: 2

sources:
  - name: brazilian_ecommerce
    description: >
      brazillian ecommerce data from kaggle
    database: dsai-module2-project
    schema: brazilian_ecommerce
    
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: products
      - name: sellers
      - name: geolocation
      - name: product_category_name_translation