version: 1
default_environment: dev
project_id: 6fb7c2fd-2809-4b1c-9cb4-d8990a709ee1
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
        - entity: customers
          path: ../data/kaggle-raw/olist_customers_dataset.csv
          keys: [customer_id]
          encoding: utf-8
        
        - entity: geolocation
          path: ../data/kaggle-raw/olist_geolocation_dataset.csv
          keys: [zip_code_prefix]
          encoding: utf-8

        - entity: order_items
          path: ../data/kaggle-raw/olist_order_items_dataset.csv
          keys: [order_id, order_item_id]
          encoding: utf-8
            
        - entity: order_payments
          path: ../data/kaggle-raw/olist_order_payments_dataset.csv
          keys: [order_id, payment_sequential]
          encoding: utf-8
            
        - entity: order_reviews
          path: ../data/kaggle-raw/olist_order_reviews_dataset.csv
          keys: [review_id]
          encoding: utf-8
            
        - entity: orders
          path: ../data/kaggle-raw/olist_orders_dataset.csv
          keys: [order_id]
          encoding: utf-8
            
        - entity: products
          path: ../data/kaggle-raw/olist_products_dataset.csv
          keys: [product_id]
          encoding: utf-8
            
        - entity: sellers
          path: ../data/kaggle-raw/olist_sellers_dataset.csv
          keys: [seller_id]
          encoding: utf-8    

        - entity: product_category_name_translation
          path: ../data/kaggle-raw/product_category_name_translation.csv
          keys: [product_category_name]
          encoding: utf-8-sig       
  loaders:
    - name: target-bigquery
      variant: z3z1ma
      pip_url: git+https://github.com/z3z1ma/target-bigquery.git
      config:
        project: dsai-module2-project
        dataset: brazilian_ecommerce
        location: US
        method: batch_job
        denormalized: true
        credentials_path: ../dsai-module2-project-c41b83e002bf.json
        batch_size: 104857600
        timeout: 600
