version: 2

models:
  - name: stg_customers
    description: >
      A staged model for raw customer data.
    columns:
      - name: customer_id
        description: The primary key of the customer record (unique to the raw table).
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: A unique identifier for the customer across all purchases.
        tests:
          - not_null
      - name: customer_city
        description: City where the customer is located.
      - name: customer_state
        description: State where the customer is located.

  - name: stg_order_items
    description: >
      A staged model for raw order line-item data.
    columns:
      - name: order_id
        description: The ID of the parent order.
        tests:
          - not_null
      - name: order_item_id
        description: The id for the item within the specific order. 
      - name: product_id
        description: The ID of the product purchased.
      - name: seller_id
        description: The ID of the seller responsible for the item.
      - name: price
        description: The price of the product.
        tests:
          - not_null

  - name: stg_orders
    description: >
      A staged model for raw order header data.
    columns:
      - name: order_id
        description: The primary key of the order.
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key linking to the stg_customers model.
        tests:
          - not_null
      - name: order_status
        description: The current status of the order
      - name: order_purchase_timestamp
        description: When the customer made the purchase.
        tests:
          - not_null

  - name: stg_order_payments
    description: >
      A staged model for raw payment details associated with an order.
    columns:
      - name: order_id
        description: Foreign key linking to the stg_orders model.
        tests:
          - not_null
      - name: payment_sequential
        description: Sequence number for payments on a single order.   
      - name: payment_type
        description: The method of payment.
      - name: payment_value
        description: The total value of the specific payment.
        tests:
          - not_null

  - name: stg_order_reviews
    description: >
      A staged model for customer review data associated with an order.
    columns:
      - name: review_id
        description: The primary key of the review.
        tests:
          - unique
          - not_null
      - name: order_id
        description: Foreign key linking to the stg_orders model.
        tests:
          - not_null
      - name: review_score
        description: The rating given by the customer.
        tests:
          - not_null

  - name: stg_products
    description: >
      A staged model for raw product master data, including categories and dimensions.
    columns:
      - name: product_id
        description: The primary key of the product.
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: The category of the product.
      - name: product_weight_g
        description: Product weight in grams.

  - name: stg_sellers
    description: >
      A staged model for raw seller master data, including location details.
    columns:
      - name: seller_id
        description: The primary key of the seller.
        tests:
          - unique
          - not_null
      - name: seller_city
        description: City where the seller is located.
      - name: seller_state
        description: State where the seller is located.
        