version: 2

models:
  - name: stg_category_translation
    description: >
      Staging model for product category name translations, cleaning and standardizing
      the category names.
    columns:
      - name: product_id
        description: Unique identifier for the product.
        tests:
          - not_null
      - name: product_category_name
        description: Original product category name, converted to lowercase.
        tests:
          - not_null
      - name: product_category_name_english
        description: English translation of the product category name, converted to lowercase.
        tests:
          - not_null

    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list: [product_id, product_category_name, product_category_name_english]

  - name: stg_customers
    description: >
      Staging model for customer data, standardizing city and state names.
    columns:
      - name: customer_id
        description: Unique identifier for a customer. Used as a foreign key in orders.
        tests:
          - not_null
      - name: customer_unique_id
        description: Identifier for customers who purchased from different locations (unique person).
        tests:
          - not_null
      - name: customer_zip_code_prefix
        description: The first 5 digits of the customer's zip code.
        tests:
          - dbt_expectations.expect_column_values_to_match_regex:
              column_name: customer_zip_code_prefix
              regex: '^[0-9]{5}$'
      - name: customer_city
        description: Customer's city, converted to lowercase.
        tests:
          - not_null
      - name: customer_state
        description: Customer's state, converted to lowercase.
        tests:
          - not_null
          - dbt_expectations.expect_column_value_lengths_to_equal:
              value: 2

    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list:
            - customer_id
            - customer_unique_id
            - customer_zip_code_prefix
            - customer_city
            - customer_state

  - name: stg_geolocation
    description: >
      Staging model for geolocation data, cleaning city and state names.
    columns:
      - name: geolocation_zip_code_prefix
        description: The first 5 digits of the zip code.
        tests:
          - not_null
      - name: geolocation_city
        description: City name, converted to lowercase.
        tests:
          - not_null
      - name: geolocation_lat
        description: Latitude coordinate.
      - name: geolocation_lng
        description: Longitude coordinate.
      - name: geolocation_state
        description: State name, converted to lowercase.
        tests:
          - not_null
          - dbt_expectations.expect_column_value_lengths_to_equal:
              value: 2

    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list:
            - geolocation_city
            - geolocation_lat
            - geolocation_lng
            - geolocation_state
            - geolocation_zip_code_prefix
            

  - name: stg_order_items
    description: >
      Staging model for items within an order, with data type casting for numeric and temporal fields.
    columns:
      - name: order_id
        description: Foreign key to the orders table.
        tests:
          - not_null
      - name: order_item_id
        description: Sequential identifier for items within the same order.
        tests:
          - not_null
      - name: product_id
        description: Foreign key to the products table.
        tests:
          - not_null
      - name: seller_id
        description: Foreign key to the sellers table.
        tests:
          - not_null
      - name: shipping_limit_date
        description: The latest date for the seller to ship the product.
      - name: price
        description: Item price, cast to NUMERIC.
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10000
      - name: freight_value
        description: Freight value of the item, cast to NUMERIC.
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1000

    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list:
            - order_id
            - order_item_id
            - product_id
            - seller_id
            - shipping_limit_date
            - price
            - freight_value

  - name: stg_order_payments
    description: >
      Staging model for order payment details, with data type casting.
    columns:
      - name: order_id
        description: Foreign key to the orders table.
        tests:
          - not_null
      - name: payment_sequential
        description: Number indicating the sequence of payment if multiple payments were made for an order.
        tests:
          - not_null
      - name: payment_type
        description: Method of payment used (e.g., 'credit_card', 'voucher').
        tests:
          - accepted_values:
              values: ['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']
      - name: payment_installments
        description: Number of installments for the payment.
      - name: payment_value
        description: Total value of the payment, cast to NUMERIC.
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 50000

    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list:
            - order_id
            - payment_sequential
            - payment_type
            - payment_installments
            - payment_value

  - name: stg_order_reviews
    description: >
      Staging model for customer order reviews, with data type casting for score and timestamps.
    columns:
      - name: review_id
        description: identifier for the review.
        tests:
          - not_null
      - name: order_id
        description: Foreign key to the orders table.
        tests:
          - not_null
      - name: review_score
        description: The score given by the customer (1 to 5), cast to INT.
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5]
              quote: False
      - name: review_creation_date
        description: Date when the review was created.
      - name: review_answer_timestamp
        description: Timestamp when the seller/system responded to the review.

    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list:
            - review_id
            - order_id
            - review_score
            - review_comment_title
            - review_comment_message
            - review_creation_date
            - review_answer_timestamp


  - name: stg_orders
    description: >
      Staging model for main order information, including crucial status and timestamp fields.
    columns:
      - name: order_id
        description: identifier for the order (Primary Key).
        tests:
          - not_null
      - name: customer_id
        description: Foreign key to the customers table.
        tests:
          - not_null
      - name: order_status
        description: Current status of the order (e.g., 'delivered', 'shipped').
        tests:
          - accepted_values:
              values: ['delivered', 'shipped', 'invoiced', 'unavailable', 'canceled', 'created', 'approved', 'processing']
      - name: order_purchase_timestamp
        description: The time when the order was purchased.
        tests:
          - not_null
      - name: order_estimated_delivery_date
        description: Estimated date for customer delivery.

    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list:
            - order_id
            - customer_id
            - order_status
            - order_purchase_timestamp
            - order_approved_at
            - order_delivered_carrier_date
            - order_delivered_customer_date
            - order_estimated_delivery_date

  - name: stg_products
    description: >
      Staging model for product catalog data, with data type casting for numerical measurements.
    columns:
      - name: product_id
        description: identifier for the product.
        tests:
          - not_null
      - name: product_category_name
        description: Original product category name (used to join with `stg_category_translation`).
      - name: product_weight_g
        description: Product weight in grams, cast to NUMERIC.
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 50000
      - name: product_length_cm
        description: Product length in centimeters, cast to NUMERIC.
      - name: product_height_cm
        description: Product height in centimeters, cast to NUMERIC.
      - name: product_width_cm
        description: Product width in centimeters, cast to NUMERIC.

    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list:
            - product_id
            - product_category_name
            - product_name_length
            - product_description_length
            - product_photos_qty
            - product_weight_g
            - product_length_cm
            - product_height_cm
            - product_width_cm

  - name: stg_sellers
    description: >
      Staging model for seller information, standardizing city and state names.
    columns:
      - name: seller_id
        description: identifier for the seller.
        tests:
          - not_null
      - name: seller_zip_code_prefix
        description: The first 5 digits of the seller's zip code.
        tests:
          - dbt_expectations.expect_column_values_to_match_regex:
              column_name: seller_zip_code_prefix
              regex: '^[0-9]{5}$'
      - name: seller_city
        description: Seller's city, converted to lowercase.
        tests:
          - not_null
      - name: seller_state
        description: Seller's state, converted to lowercase.
        tests:
          - not_null
          - dbt_expectations.expect_column_value_lengths_to_equal:
              value: 2

    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list:
            - seller_id
            - seller_zip_code_prefix
            - seller_city
            - seller_state