brazillian_ecommerce_project:
  outputs:
    dev:
      dataset: brazilian_ecommerce
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: service-account
      keyfile: /opt/project/dsai-module2-project-c41b83e002bf.json
      priority: interactive
      project: dsai-module2-project
      threads: 1
      type: bigquery
  target: dev